### GET request with a header
GET http://localhost:3000
Accept: application/json

### Post Request
POST http://localhost:3000
Content-Type: application/json

{
  "id": 999,
  "name": "content"
}

### Get Request with query
GET http://localhost:3000/query/?id=1&name=jobeyer sheikh
Accept: application/json

### Get Request with parameter
GET http://localhost:3000/param/01752062838
Accept: application/json

### Get Request with query-parameter
GET http://localhost:3000/param-query/01752062838/?id=1&name=jobeyer sheikh
Accept: application/json

### Order Message Post
POST http://localhost:3000/api/order-message
Accept: application/json
Content-Type: application/json

### RabbitMQ health check
GET http://localhost:3000/api/rabbitmq/_health
Accept: application/json
Content-Type: application/json

### Get Order Message
GET http://localhost:3000/api/order-message/?page=1&limit=20&orderId=1&customerId=1&lineOfBusiness=1
Accept: application/json
Content-Type: application/json

### Post Order Message
POST http://localhost:3000/api/order-message
Content-Type: application/json

{
  "orderId": 1,
  "customerId": 1,
  "lineOfBusiness": 2,
  "phone": "01752062838",
  "orderStatus": "Success",
  "text": "Hello",
  "delivered": true
}

### Check Brac Net API

POST https://sms.bracnet.net/smsapi
Content-Type: application/json

{
  "api_key" : "C3000010644cf4bc808c37.91444038",
  "senderid" : "8809677399956",
  "type" : "text/unicode",
  "msg" : "Hello World",
  "contacts" : "8801752062838"
}